### ISSUE TITLE
Alembic Animation Cache optional

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-maya#66] opened 2024-08-11 18:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

When animation is published from the rig, animation is always published as alembic. We need control to disable alembic animation (because studio can use FBX output)

### How would you imagine the implementation of the feature?

Add control to the settings to disable per-project alembic cache instance to be published

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by BigRoy** [comment] 2024-08-14 09:25
Duplicate of https://github.com/ynput/ayon-maya/issues/36

**Comment by BigRoy** [comment] 2024-09-04 07:00
Closing as it is a duplicate

**Closed by BigRoy** 2024-09-04 07:00 UTC
Labels: enhancement
